"""Google-Maps-style web app: drag around a continuous, never-existing satellite map
generated by the trained decoders. Switch between the one-step and diffusion decoders
with the dropdown.

Each visible tile is decoded from a padded window into the shared deterministic
embedding field (field.py) -- padding with real neighboring field context and cropping
after decoding is what keeps features that span a tile boundary (e.g. a house) coherent
across tiles, instead of getting cut off. See field.py's module docstring for the full
design.

PCA is fit once (GPU SVD) and cached to checkpoints/pca_model.pt -- subsequent launches
just load it. Generated tiles are cached in memory per (model, x, y) since the field is
revisit-stable (deterministic), so panning back to a spot doesn't regenerate it.

Not run locally in this session -- executed on cloud compute by the user. The Flask dev
server binds 0.0.0.0:5000; if running on a remote/cluster node, port-forward or tunnel
to view it in a browser.
"""

import io
import json

import numpy as np
import torch
from flask import Flask, Response, jsonify, render_template_string, request

import classify
import config
import field
from generate_novel import to_uint8_image
from models import DiffusionUNet, OneStepDecoder
from skimage.io import imsave
from train_diffusion_decoder import GaussianDiffusion

app = Flask(__name__)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
_state = {"models": {}, "tile_cache": {}}


def load_all_regions():
    with open(config.REGIONS_FILE) as f:
        n_regions = len(json.load(f)["names"])
    with open(f"{config.DATA_DIR}/norm_stats.json") as f:
        stats = json.load(f)
    mean = np.array(stats["mean"], dtype=np.float32)
    std = np.array(stats["std"], dtype=np.float32)

    embeddings_norm = [(np.load(config.embedding_cache(i)) - mean) / std for i in range(n_regions)]
    train_coords = np.load(f"{config.DATA_DIR}/train_coords.npy")
    return embeddings_norm, train_coords


def load_field_inputs(embeddings_norm, train_coords):
    """PCA is fit pooling pixels across every region (terrain variety), but the live
    map's real-crop grounding texture is tiled from a single region (config.
    GROUNDING_REGION_INDEX) to avoid a visible seam where it would otherwise jump
    between terrain types."""
    pca_mean, components, explained_variance = field.fit_or_load_pca(embeddings_norm, train_coords, device=DEVICE)
    grounding = embeddings_norm[config.GROUNDING_REGION_INDEX]
    return grounding, pca_mean, components, explained_variance


def get_onestep():
    if "onestep" not in _state["models"]:
        model = OneStepDecoder(in_ch=config.EMBEDDING_DIM).to(DEVICE)
        model.load_state_dict(torch.load(config.ONESTEP_CHECKPOINT, map_location=DEVICE)["model_state_dict"])
        model.eval()
        _state["models"]["onestep"] = model
    return _state["models"]["onestep"]


def get_diffusion():
    if "diffusion" not in _state["models"]:
        ckpt = torch.load(config.DIFFUSION_CHECKPOINT, map_location=DEVICE)
        model = DiffusionUNet(embedding_dim=config.EMBEDDING_DIM).to(DEVICE)
        model.load_state_dict(ckpt["model_state_dict"])
        model.eval()
        diffusion = GaussianDiffusion(timesteps=ckpt["timesteps"], device=DEVICE)
        _state["models"]["diffusion"] = (model, diffusion)
    return _state["models"]["diffusion"]


def render_tile(model_name, tile_x, tile_y):
    size = config.GEN_TILE_SIZE
    margin = config.DECODE_MARGIN
    x0, y0 = tile_x * size - margin, tile_y * size - margin
    w = h = size + 2 * margin

    embedding_norm, pca_mean, components, explained_variance = _state["field_inputs"]
    grid = field.embedding_window(x0, y0, w, h, pca_mean, components, explained_variance, embedding_norm)
    emb_tensor = torch.from_numpy(grid).float().permute(2, 0, 1)[None].to(DEVICE)

    if model_name == "diffusion":
        model, diffusion = get_diffusion()
        tile_seed = ((int(tile_x) * 0x9E3779B1) ^ (int(tile_y) * 0x85EBCA6B) ^ 0x2545F491) & 0xFFFFFFFF
        generator = torch.Generator(device=DEVICE).manual_seed(tile_seed)
        with torch.no_grad():
            pred_full = diffusion.ddim_sample(model, emb_tensor, steps=config.DDIM_STEPS, generator=generator)[0]
    else:
        model = get_onestep()
        with torch.no_grad():
            pred_full = model(emb_tensor)[0]

    crop = pred_full[:, margin : margin + size, margin : margin + size]
    img = to_uint8_image(crop)

    centers, threshold = _state["classify"]
    visible_grid = grid[margin : margin + size, margin : margin + size, :]
    if classify.novelty_score(visible_grid, centers, device=DEVICE) < threshold:
        b = config.NOVELTY_BORDER_PX
        img[:b, :, :] = [255, 0, 0]
        img[-b:, :, :] = [255, 0, 0]
        img[:, :b, :] = [255, 0, 0]
        img[:, -b:, :] = [255, 0, 0]

    buf = io.BytesIO()
    imsave(buf, img, format="png", check_contrast=False)
    return buf.getvalue()


@app.route("/tile/<model_name>/<int:x>/<int:y>.png")
def tile(model_name, x, y):
    key = (model_name, x, y)
    if key not in _state["tile_cache"]:
        _state["tile_cache"][key] = render_tile(model_name, x, y)
    return Response(_state["tile_cache"][key], mimetype="image/png")


@app.route("/heatmap/<int:x>/<int:y>.png")
def heatmap(x, y):
    size = config.GEN_TILE_SIZE
    embedding_norm, pca_mean, components, explained_variance = _state["field_inputs"]
    grid = field.embedding_window(x * size, y * size, size, size, pca_mean, components, explained_variance, embedding_norm)

    centers, _ = _state["classify"]
    colors = classify.classify_grid(grid, centers, _state["labels"], device=DEVICE)
    alpha = np.full((size, size, 1), 160, dtype=np.uint8)
    rgba = np.concatenate([colors, alpha], axis=-1)

    buf = io.BytesIO()
    imsave(buf, rgba, format="png", check_contrast=False)
    return Response(buf.getvalue(), mimetype="image/png")


@app.route("/label", methods=["POST"])
def add_label():
    payload = request.get_json(force=True)
    x, y = int(payload["x"]), int(payload["y"])
    name = str(payload.get("name", "")).strip()
    if not name:
        return jsonify({"error": "empty name"}), 400

    embedding_norm, pca_mean, components, explained_variance = _state["field_inputs"]
    patch = field.embedding_window(x - 4, y - 4, 8, 8, pca_mean, components, explained_variance, embedding_norm)
    vector = patch.reshape(-1, config.EMBEDDING_DIM).mean(axis=0).tolist()

    _state["labels"].append({"x": x, "y": y, "name": name, "vector": vector})
    classify.save_labels(_state["labels"])
    return jsonify({"ok": True, "n_labels": len(_state["labels"])})


PAGE = """
<!doctype html>
<html>
<head>
<title>Tessera Novel Maps</title>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
<style>
  html, body { margin: 0; height: 100%; font-family: sans-serif; }
  #controls { position: absolute; z-index: 1000; top: 10px; left: 50px; background: white;
              padding: 6px 10px; border-radius: 4px; box-shadow: 0 1px 4px rgba(0,0,0,0.3);
              display: flex; gap: 10px; align-items: center; flex-wrap: wrap; max-width: 70vw; }
  #map { height: 100%; background: #111; }
  #map.labeling { cursor: crosshair; }
  #controls span { font-size: 12px; color: #555; }
</style>
</head>
<body>
  <div id="controls">
    <label>Decoder:
      <select id="model">
        <option value="onestep">One-step</option>
        <option value="diffusion">Diffusion</option>
      </select>
    </label>
    <label><input type="checkbox" id="heatmap-toggle"> Region heatmap</label>
    <button id="label-btn">Add label</button>
    <span>Red border = tile close to a real observed location</span>
  </div>
  <div id="map"></div>
<script>
const map = L.map('map', {crs: L.CRS.Simple, minZoom: 0, maxZoom: 0}).setView([0, 0], 0);
let layer, heatLayer;
let heatmapOn = false;
let heatmapVersion = 0;
let labeling = false;

function setLayer(model) {
  if (layer) map.removeLayer(layer);
  layer = L.tileLayer(`/tile/${model}/{x}/{y}.png`, {tileSize: __TILE_SIZE__, noWrap: false}).addTo(map);
}
setLayer('onestep');

function refreshHeatmap() {
  if (heatLayer) { map.removeLayer(heatLayer); heatLayer = null; }
  if (heatmapOn) {
    heatLayer = L.tileLayer(`/heatmap/{x}/{y}.png?v=${heatmapVersion}`, {tileSize: __TILE_SIZE__, noWrap: false, opacity: 0.6}).addTo(map);
  }
}

document.getElementById('model').addEventListener('change', e => setLayer(e.target.value));
document.getElementById('heatmap-toggle').addEventListener('change', e => { heatmapOn = e.target.checked; refreshHeatmap(); });

const labelBtn = document.getElementById('label-btn');
labelBtn.addEventListener('click', () => {
  labeling = !labeling;
  labelBtn.textContent = labeling ? 'Click map to label...' : 'Add label';
  document.getElementById('map').classList.toggle('labeling', labeling);
});

map.on('click', async (e) => {
  if (!labeling) return;
  labeling = false;
  labelBtn.textContent = 'Add label';
  document.getElementById('map').classList.remove('labeling');

  const name = prompt('Label this region (e.g. city, lake, hill):');
  if (!name) return;

  const pt = map.project(e.latlng, 0);
  await fetch('/label', {
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    body: JSON.stringify({x: Math.round(pt.x), y: Math.round(pt.y), name}),
  });
  heatmapVersion++;
  refreshHeatmap();
});
</script>
</body>
</html>
""".replace("__TILE_SIZE__", str(config.GEN_TILE_SIZE))


@app.route("/")
def index():
    return render_template_string(PAGE)


if __name__ == "__main__":
    print("Loading regions...")
    embeddings_norm, train_coords = load_all_regions()

    print("Fitting/loading PCA (pooled across all regions)...")
    _state["field_inputs"] = load_field_inputs(embeddings_norm, train_coords)

    print("Building/loading region-classifier reference bank...")
    _state["classify"] = classify.build_or_load_bank(embeddings_norm, train_coords, device=DEVICE)
    _state["labels"] = classify.load_labels()
    print(f"  {len(_state['labels'])} saved label(s) loaded")

    print("Ready.")
    app.run(host="0.0.0.0", port=5000)
