"""Google-Maps-style web app: drag around a continuous, never-existing satellite map
generated by the trained decoders. Switch between the one-step and diffusion decoders
with the dropdown.

Each visible tile is decoded from a padded window into the shared deterministic
embedding field (field.py) -- padding with real neighboring field context and cropping
after decoding is what keeps features that span a tile boundary (e.g. a house) coherent
across tiles, instead of getting cut off. See field.py's module docstring for the full
design.

PCA is fit once (GPU SVD) and cached to checkpoints/pca_model.pt -- subsequent launches
just load it. Generated tiles are cached in memory per (model, x, y) since the field is
revisit-stable (deterministic), so panning back to a spot doesn't regenerate it.

Not run locally in this session -- executed on cloud compute by the user. The Flask dev
server binds 0.0.0.0:5000; if running on a remote/cluster node, port-forward or tunnel
to view it in a browser.
"""

import io
import json

import numpy as np
import torch
from flask import Flask, Response, render_template_string

import config
import field
from generate_novel import to_uint8_image
from models import DiffusionUNet, OneStepDecoder
from skimage.io import imsave
from train_diffusion_decoder import GaussianDiffusion

app = Flask(__name__)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
_state = {"models": {}, "tile_cache": {}}


def load_field_inputs():
    embedding = np.load(config.EMBEDDING_CACHE)
    train_coords = np.load(f"{config.DATA_DIR}/train_coords.npy")
    with open(f"{config.DATA_DIR}/norm_stats.json") as f:
        stats = json.load(f)
    mean = np.array(stats["mean"], dtype=np.float32)
    std = np.array(stats["std"], dtype=np.float32)
    embedding_norm = (embedding - mean) / std
    pca_mean, components, explained_variance = field.fit_or_load_pca(embedding_norm, train_coords, device=DEVICE)
    return embedding_norm, pca_mean, components, explained_variance


def get_onestep():
    if "onestep" not in _state["models"]:
        model = OneStepDecoder(in_ch=config.EMBEDDING_DIM).to(DEVICE)
        model.load_state_dict(torch.load(config.ONESTEP_CHECKPOINT, map_location=DEVICE)["model_state_dict"])
        model.eval()
        _state["models"]["onestep"] = model
    return _state["models"]["onestep"]


def get_diffusion():
    if "diffusion" not in _state["models"]:
        ckpt = torch.load(config.DIFFUSION_CHECKPOINT, map_location=DEVICE)
        model = DiffusionUNet(embedding_dim=config.EMBEDDING_DIM).to(DEVICE)
        model.load_state_dict(ckpt["model_state_dict"])
        model.eval()
        diffusion = GaussianDiffusion(timesteps=ckpt["timesteps"], device=DEVICE)
        _state["models"]["diffusion"] = (model, diffusion)
    return _state["models"]["diffusion"]


def render_tile(model_name, tile_x, tile_y):
    size = config.GEN_TILE_SIZE
    margin = config.DECODE_MARGIN
    x0, y0 = tile_x * size - margin, tile_y * size - margin
    w = h = size + 2 * margin

    embedding_norm, pca_mean, components, explained_variance = _state["field_inputs"]
    grid = field.embedding_window(x0, y0, w, h, pca_mean, components, explained_variance, embedding_norm)
    emb_tensor = torch.from_numpy(grid).float().permute(2, 0, 1)[None].to(DEVICE)

    if model_name == "diffusion":
        model, diffusion = get_diffusion()
        tile_seed = ((int(tile_x) * 0x9E3779B1) ^ (int(tile_y) * 0x85EBCA6B) ^ 0x2545F491) & 0xFFFFFFFF
        generator = torch.Generator(device=DEVICE).manual_seed(tile_seed)
        with torch.no_grad():
            pred_full = diffusion.ddim_sample(model, emb_tensor, steps=config.DDIM_STEPS, generator=generator)[0]
    else:
        model = get_onestep()
        with torch.no_grad():
            pred_full = model(emb_tensor)[0]

    crop = pred_full[:, margin : margin + size, margin : margin + size]
    buf = io.BytesIO()
    imsave(buf, to_uint8_image(crop), format="png", check_contrast=False)
    return buf.getvalue()


@app.route("/tile/<model_name>/<int:x>/<int:y>.png")
def tile(model_name, x, y):
    key = (model_name, x, y)
    if key not in _state["tile_cache"]:
        _state["tile_cache"][key] = render_tile(model_name, x, y)
    return Response(_state["tile_cache"][key], mimetype="image/png")


PAGE = """
<!doctype html>
<html>
<head>
<title>Tessera Novel Maps</title>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
<style>
  html, body { margin: 0; height: 100%; font-family: sans-serif; }
  #controls { position: absolute; z-index: 1000; top: 10px; left: 50px; background: white;
              padding: 6px 10px; border-radius: 4px; box-shadow: 0 1px 4px rgba(0,0,0,0.3); }
  #map { height: 100%; background: #111; }
</style>
</head>
<body>
  <div id="controls">
    <label>Decoder:
      <select id="model">
        <option value="onestep">One-step</option>
        <option value="diffusion">Diffusion</option>
      </select>
    </label>
  </div>
  <div id="map"></div>
<script>
const map = L.map('map', {crs: L.CRS.Simple, minZoom: 0, maxZoom: 0}).setView([0, 0], 0);
let layer;
function setLayer(model) {
  if (layer) map.removeLayer(layer);
  layer = L.tileLayer(`/tile/${model}/{x}/{y}.png`, {tileSize: %(tile_size)d, noWrap: false}).addTo(map);
}
setLayer('onestep');
document.getElementById('model').addEventListener('change', e => setLayer(e.target.value));
</script>
</body>
</html>
""" % {"tile_size": config.GEN_TILE_SIZE}


@app.route("/")
def index():
    return render_template_string(PAGE)


if __name__ == "__main__":
    print("Loading data and fitting/loading PCA...")
    _state["field_inputs"] = load_field_inputs()
    print("Ready.")
    app.run(host="0.0.0.0", port=5000)
